### ISSUE TITLE
Support for docker build `--file` flag

### ISSUE THREAD

**Issue by psychowico** [docker/fig#976] opened 2015-02-17 14:22 UTC
From changelog:
```
1.5.0 (2015-02-10)

Builder

* Dockerfile to use for a given docker build can be specified with the -f flag
```

It's means that we can point our Dockerfile in diffrent place than `context` directory is, for example:
```
docker build -f ./backend/Dockerfile .
```
(Context is current directory, dockerfile is inside ./backend directory)

So, we need new yaml key to support this.

I propose left `build` key and simply add `Dockerfile` key, to support this flag.

**Comment by md5** [comment] 2015-02-17 14:35
This is a duplicate of #834

**Comment by dnephin** [comment] 2015-02-17 15:26
Yup, closing as duplicate

**Closed by dnephin** 2015-02-17 15:26 UTC
