### ISSUE TITLE
Setting lantency between container starting sequence when using fig up -d ?

### ISSUE THREAD

**Issue by allencloud** [docker/fig#899] opened 2015-01-29 04:43 UTC
Today I ran into such kind of problem.

when I run `fig up -d` with the fig.yml like below:
<pre>service:
  image: service
  ports:
    - "1234:1234"
  links:
    - mysql:mysql
  command: service
mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=xxxxxx
    - MYSQL_DATABASE=xxxxxx
  ports:
    - "3306:3306" </pre>

Although fig will check the starting sequence of service and mysql, and start mysql firstly, then service.
Here is the sequence:
1.create container "mysql", OK
2.start container "mysql", starting........... seems OK
3.create container "service", do the linking thing
4.start container "service", as "service" needs to connect "mysql", However the mysqld process in "mysql" still hasn't finished.  As a result, "service" starting fails.
5.start container "mysql", completed !

At first, I doubt that whether my fig.yml is not in correct format, However when I did `fig up -d` repeatedly in 10 times, there is once that I succeeded in making "service" and "mysql" both  running. In the 9 failed times, when I manually ran `docker start service`, "service" could be started completely. Such experience made to realise this kind of situation.

If what I said is reasonable, I suggest that fig should add some latency into the linking container starting sequence.

**Comment by dnephin** [comment] 2015-01-29 04:46
Duplicate of #374

It might be good to have a "Compose Patterns" document somewhere that we can call out ways to handle common problems.

**Closed** 2015-01-31 17:17 UTC
