### ISSUE TITLE
fig up tries to run incorrect command

### ISSUE THREAD

**Issue by jbulchergist** [docker/fig#843] opened 2015-01-14 01:29 UTC
I have a *data container* build from *scratch* with nothing but a file called `/true` init, so that fig is able to start up the container (it would be nice if I didn't even need that file). Fig starts the container fine the first time, but attempting to run `fig up` on the service after bringing it down results in an odd message:

`Cannot start container 12341234...: exec: "/bin/echo": stat /bin/echo: no such file or directory`

I don't want fig runing echo - I want to run `/true`, if anything.

```Dockerfile
FROM scratch

COPY true /true

CMD [ "/true" ]
```

Shouldn't fig respect `CMD`? Can I make it respect `CMD`?

**Comment by dnephin** [comment] 2015-01-14 01:55
I think this is a duplicate of #613 and #517

**Comment by dnephin** [comment] 2015-01-21 01:54
Tracking this in #613, the workaround for now is to use `busybox` or a container that has `/bin/echo`

**Closed by dnephin** 2015-01-21 01:54 UTC
