### ISSUE TITLE
Project Name part of fig.yml

### ISSUE THREAD

**Issue by kameshsampath** [docker/fig#885] opened 2015-01-26 15:34 UTC
Right now we don't have the ability to add project name to the fig.yml, it will be great to add as then fig.yml will be one source of informaiton about the project.

-Kamesh

**Comment by dnephin** [comment] 2015-01-26 15:37
Duplicate of #45

**Closed by dnephin** 2015-01-26 15:37 UTC

**Comment by kameshsampath** [comment] 2015-01-26 15:40
Ok thanks.
