### ISSUE TITLE
Python3 compatible

### ISSUE THREAD

**Issue by wernight** [docker/fig#884] opened 2015-01-26 13:20 UTC
Please make it also Python3 compatible, should be easy to convert using `2to3` but you can make it Python 2 and Python 3 compatible via:

    $ pip install modernize
    $ python-modernize -w my_script.py

**Comment by dnephin** [comment] 2015-01-26 15:30
Duplicate of #219 (see also #440)

**Closed by dnephin** 2015-01-26 15:30 UTC
